server:
  port: 8001


spring:
  application:
    name: cloud-privider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.204.100:3306/spring_cloud_payment?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.xiaoxuan.springcloud.entities   # 所有Entity别名类所在的包


